Beac 67 remove rest calls
venicegeo/piazza pull request #9
Opened 2018-11-29 17:42 UTC by fsufitch

2018-12-03 13:22 UTC, go0ty requested changes

2018-12-12 00:35 UTC, fsufitch commented on src/main/java/org/venice/piazza/gateway/controller/AdminController.java
> +	private org.venice.piazza.idam.controller.AdminController idamAdminController;
Because we're using a different class called `AdminController` in a class already called `AdminController`.

2018-12-12 00:35 UTC, fsufitch commented on src/main/java/org/venice/piazza/gateway/controller/AdminController.java
> +import org.venice.piazza.idam.controller.AuthController;
I am open to changing these names from controllers to something else, but in the first pass I kept them the way they originally were.

2018-12-12 00:39 UTC, fsufitch commented on src/main/java/org/venice/piazza/gateway/controller/AdminController.java
> +				// TODO
The TODO was to verify that the response structure still matches the expected one, but upon further inspection, it's not necessary. If it breaks, it breaks, and we'll iron it out in the debug stage of the migration.

2018-12-12 00:40 UTC, fsufitch commented on src/main/java/org/venice/piazza/gateway/controller/DeploymentController.java
> +			String.format("%s/deployment/group/%s", ACCESS_URL, deploymentGroupId);
Done. I'd missed it.

2018-12-12 00:41 UTC, fsufitch commented on src/main/resources/pz-release.json
> +{"version": "1.0.0-243-g3242324","components":{"pz-access":"Sprint06-109-gbf4e453","pz-docs":"ebf10e4","pz-gateway":"Sprint06-234-gc5c4405","pz-ingest":"Sprint06-73-ge906026","pz-jobmanager":"Sprint0
This is a placeholder for things to work as a stopgap. We will need to address how it gets generated for this new project when we deploy it.

2018-12-12 00:41 UTC, fsufitch commented on src/main/java/org/venice/piazza/gateway/controller/ServiceController.java
> +	private org.venice.piazza.servicecontroller.controller.ServiceController serviceControllerController;
Because we're using a class called `ServiceController` inside of a different class called `ServiceController`.

2018-12-12 00:41 UTC, fsufitch commented on src/main/java/org/venice/piazza/gateway/controller/ServiceController.java
> +	private org.venice.piazza.servicecontroller.controller.ServiceController serviceControllerController;
Should probably rename one of the two, but I'm open for suggestions.

2018-12-12 00:42 UTC, fsufitch commented on src/main/java/org/venice/piazza/gateway/controller/AdminController.java
> +	private org.venice.piazza.idam.controller.AdminController idamAdminController;
Should probably rename one of the two, but I'm open for suggestions.

2018-12-12 12:13 UTC, go0ty approved these changes
Looks good - just check the one comment where we'll want to delete the version json file and add to the JenkinsFile.

2018-12-12 12:13 UTC, go0ty commented on src/main/resources/pz-release.json
> +{"version": "1.0.0-243-g3242324","components":{"pz-access":"Sprint06-109-gbf4e453","pz-docs":"ebf10e4","pz-gateway":"Sprint06-234-gc5c4405","pz-ingest":"Sprint06-73-ge906026","pz-jobmanager":"Sprint0
https://github.com/venicegeo/pz-gateway/blob/master/JenkinsFile#L41

This is the way it's currently being done. Let's move this into the JenkinsFile if it's not already -- then we can delete this pz-release.json file from source.

2018-12-12 15:18 UTC, merged